<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Services\InventoryAnalyticsService;
use App\Models\PurchasePlan;
use App\Models\PurchasePlanItem;
use Carbon\Carbon;

class GenerateSmartReorderPlan extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:generate-smart-reorder-plan';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Automatically generate a Purchase Plan for items that reached their reorder level.';

    /**
     * Execute the console command.
     */
    public function handle(InventoryAnalyticsService $inventoryAnalytics)
    {
        $this->info('Starting Smart Reorder generation...');

        $suggestions = $inventoryAnalytics->getSmartReorderSuggestions();

        if ($suggestions->isEmpty()) {
            $this->info('No products require reordering today.');
            return;
        }

        // Create a new Purchase Plan
        $plan = PurchasePlan::create([
            'plan_date' => Carbon::today(),
            'status' => 'Draft',
            'notes' => 'Auto-generated by Smart Reorder CRON.'
        ]);

        $itemCount = 0;
        foreach ($suggestions as $product) {
            // Default suggested quantity: Maximum Stock - Available Stock (or at least 1)
            $requiredQuantity = $product->maximum_stock > $product->available_stock 
                ? ($product->maximum_stock - $product->available_stock) 
                : 1;

            PurchasePlanItem::create([
                'purchase_plan_id' => $plan->id,
                'product_id' => $product->id,
                'required_quantity' => $requiredQuantity,
                'suggested_vendor_id' => null, // Can be enhanced later
            ]);
            $itemCount++;
        }

        $this->info("Successfully generated Purchase Plan ID {$plan->id} with {$itemCount} items.");
    }
}
