<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Purchase Voucher - {{ $voucher->voucher_number }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 14px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h2 { margin: 0; color: #4e73df; }
        .info-table { width: 100%; margin-bottom: 20px; }
        .info-table td { padding: 5px; vertical-align: top; }
        .details-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .details-table th, .details-table td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        .details-table th { background-color: #f8f9fc; }
        .text-right { text-align: right; }
        .total-row th { background-color: #eaecf4; font-size: 16px; }
        .footer { margin-top: 50px; font-size: 12px; color: #777; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h2>PURCHASE VOUCHER</h2>
        <p>Voucher No: <strong>{{ $voucher->voucher_number }}</strong> | Date: {{ \Carbon\Carbon::parse($voucher->date)->format('d-M-Y') }}</p>
    </div>

    <table class="info-table">
        <tr>
            <td width="50%">
                <strong>Vendor Details:</strong><br>
                @if($voucher->reference && $voucher->reference->vendor)
                    {{ $voucher->reference->vendor->company_name }}<br>
                    Vendor Code: {{ $voucher->reference->vendor->vendor_code }}
                @else
                    N/A
                @endif
            </td>
            <td width="50%" class="text-right">
                <strong>Purchase Order:</strong> {{ $voucher->reference->po_number ?? 'N/A' }}<br>
                <strong>Vendor Inv No:</strong> {{ $voucher->metadata['vendor_invoice_number'] ?? 'N/A' }}<br>
                <strong>Vendor Inv Date:</strong> {{ isset($voucher->metadata['vendor_invoice_date']) ? \Carbon\Carbon::parse($voucher->metadata['vendor_invoice_date'])->format('d-M-Y') : 'N/A' }}
            </td>
        </tr>
    </table>

    <table class="details-table">
        <thead>
            <tr>
                <th>Product</th>
                <th>Qty</th>
                <th>Rate</th>
                <th class="text-right">Amount (₹)</th>
            </tr>
        </thead>
        <tbody>
            @php $lines = $voucher->metadata['lines'] ?? []; @endphp
            @foreach($lines as $line)
                @php $product = \App\Models\Product::find($line['product_id']); @endphp
                <tr>
                    <td>{{ $product->item_name ?? 'Unknown' }}</td>
                    <td>{{ $line['invoiced_qty'] }}</td>
                    <td>{{ number_format($line['unit_price'], 2) }}</td>
                    <td class="text-right">{{ number_format($line['amount'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3" class="text-right">Taxable Amount:</th>
                <th class="text-right">{{ number_format($voucher->metadata['total_taxable'] ?? 0, 2) }}</th>
            </tr>
            <tr>
                <th colspan="3" class="text-right">CGST:</th>
                <th class="text-right">{{ number_format($voucher->metadata['total_cgst'] ?? 0, 2) }}</th>
            </tr>
            <tr>
                <th colspan="3" class="text-right">SGST:</th>
                <th class="text-right">{{ number_format($voucher->metadata['total_sgst'] ?? 0, 2) }}</th>
            </tr>
            <tr>
                <th colspan="3" class="text-right">IGST:</th>
                <th class="text-right">{{ number_format($voucher->metadata['total_igst'] ?? 0, 2) }}</th>
            </tr>
            <tr class="total-row">
                <th colspan="3" class="text-right">Grand Total (₹):</th>
                <th class="text-right">{{ number_format($voucher->metadata['grand_total'] ?? 0, 2) }}</th>
            </tr>
        </tfoot>
    </table>

    <div>
        <strong>Narration:</strong>
        <p>{{ $voucher->narration ?: 'N/A' }}</p>
    </div>

    <div class="footer">
        Generated by Demo ERP System on {{ now()->format('d-M-Y H:i:s') }}
    </div>
</body>
</html>
