<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Debit Note - {{ $voucher->voucher_number }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 14px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h2 { margin: 0; color: #4e73df; }
        .info-table { width: 100%; margin-bottom: 20px; }
        .info-table td { padding: 5px; vertical-align: top; }
        .details-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .details-table th, .details-table td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        .details-table th { background-color: #f8f9fc; }
        .text-right { text-align: right; }
        .total-row th { background-color: #eaecf4; font-size: 16px; }
        .footer { margin-top: 50px; font-size: 12px; color: #777; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h2>DEBIT NOTE (PURCHASE RETURN)</h2>
        <p>Debit Note No: <strong>{{ $voucher->voucher_number }}</strong> | Date: {{ \Carbon\Carbon::parse($voucher->date)->format('d-M-Y') }}</p>
    </div>

    <table class="info-table">
        <tr>
            <td width="50%">
                <strong>Vendor Details:</strong><br>
                @if($voucher->metadata && isset($voucher->metadata['vendor_id']))
                    @php $vData = \App\Models\Vendor::find($voucher->metadata['vendor_id']); @endphp
                    {{ $vData->company_name ?? 'N/A' }}<br>
                    Vendor Code: {{ $vData->vendor_code ?? 'N/A' }}
                @else
                    N/A
                @endif
            </td>
            <td width="50%" class="text-right">
                <strong>Original Purchase Voucher:</strong> {{ $voucher->metadata['original_purchase_voucher_number'] ?? 'N/A' }}<br>
                <strong>Reason for Return:</strong> {{ $voucher->metadata['reason'] ?? 'N/A' }}
            </td>
        </tr>
    </table>

    <table class="details-table">
        <thead>
            <tr>
                <th>Product</th>
                <th>Return Qty</th>
                <th>Original Rate</th>
                <th class="text-right">Taxable Value (₹)</th>
            </tr>
        </thead>
        <tbody>
            @php $lines = $voucher->metadata['lines'] ?? []; @endphp
            @foreach($lines as $line)
                @php $product = \App\Models\Product::find($line['product_id']); @endphp
                <tr>
                    <td>{{ $product->item_name ?? 'Unknown' }}</td>
                    <td>{{ $line['return_qty'] }}</td>
                    <td>{{ number_format($line['unit_price'], 2) }}</td>
                    <td class="text-right">{{ number_format($line['amount'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3" class="text-right">Total Taxable Value:</th>
                <th class="text-right">{{ number_format($voucher->metadata['total_taxable'] ?? 0, 2) }}</th>
            </tr>
            <tr>
                <th colspan="3" class="text-right">CGST Reversal:</th>
                <th class="text-right">{{ number_format($voucher->metadata['total_cgst'] ?? 0, 2) }}</th>
            </tr>
            <tr>
                <th colspan="3" class="text-right">SGST Reversal:</th>
                <th class="text-right">{{ number_format($voucher->metadata['total_sgst'] ?? 0, 2) }}</th>
            </tr>
            <tr>
                <th colspan="3" class="text-right">IGST Reversal:</th>
                <th class="text-right">{{ number_format($voucher->metadata['total_igst'] ?? 0, 2) }}</th>
            </tr>
            <tr class="total-row">
                <th colspan="3" class="text-right">Grand Total (₹):</th>
                <th class="text-right">{{ number_format($voucher->metadata['grand_total'] ?? 0, 2) }}</th>
            </tr>
        </tfoot>
    </table>

    <div>
        <strong>Narration:</strong>
        <p>{{ $voucher->narration ?: 'N/A' }}</p>
    </div>

    <div class="footer">
        Generated by Demo ERP System on {{ now()->format('d-M-Y H:i:s') }}
    </div>
</body>
</html>
